# Site settings
title: IAMonoid
email: matt@wiredthing.com
description: Wandering cloud of thoughts in a functional world
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iamonoid.com" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/matt', 'fa-user']
single_footer: '<p>The writer community loves your content. Writer &copy; 2015 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['IAMonoid 2015', '/about']


# Build settings
markdown: kramdown
